spring:
  freemarker:
    expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
    jpa:
      hibernate.ddl-auto: update
      show-sql: admin
server:
  port : 8081
